ferris: Remove IGNORE_MOD_TAP_INTERRUPT
After rebasing on top of 0.21.6, this needs to be explicitly removed
otherwise qmk would just fail to build:

quantum/action_tapping.c:15:10: error: #error "IGNORE_MOD_TAP_INTERRUPT
is no longer necessary as it is now the default behavior of mod-tap
keys. Please remove it from your config."

Signed-off-by: Wen-chien Jesse Sung <jesse@cola.voip.idv.tw>